### PR TITLE
Fixed the footer and added icons for socials

### PR DESCRIPTION
**Pull request by aysh2603**

### CODE REVIEW

**Comment by Abhilasha6** [comment]
can you send me the link after you fixed the website ?

**Comment by aysh2603** [comment]
I have created a PR, you can see it in your dev environment. I don't know how can I share the website link.

**Comment by Abhilasha6** [comment]
well done !

**Comment by aysh2603** [comment]
Thank You.
Please add hackodex2023-accepted label in the merged PR.

**Comment by Abhilasha6** [comment]
done

**Pull request merged**
