### PR TITLE
Badges and Inventory pages added

### PR DESCRIPTION
**Pull request by vinayakmalviya21**
Issue No. #3 

- [x] Badges page done
- [x] Inventory page done
- [x] Both page is responsive

### CODE REVIEW

**Comment by vinayakmalviya21** [comment]
Issue no. #5
I have made landing page responsive.

**Comment by Abhilasha6** [comment]
can you send me a screenshot of the pages you created ?

**Review by Abhilasha6 — COMMENTED** [review]
2nd sword jfif is not loading,  pls look into it

**Review by Abhilasha6 — COMMENTED** [review]
vehicles and weapons in the inventory page are also unavailable, recheck them. Good job !

**Review by Abhilasha6 — APPROVED** [review]

**Comment by vinayakmalviya21** [comment]
Badges page
Inventory page

**Pull request merged**
